export default [
  {
    id: "qwe;jkl",
    title: "Complete project",
    content:
      "Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing Finish coding and testing ",
    background: "hsl(50,80%,50%)",
    size: 40,
    category: "Work",
    creationDate: new Date("2023-04-22T10:30:00.000Z"),
    expirationDate: new Date("2023-04-22T10:30:00.000Z"),
    isPinned: true,
    isHidden: false,
    boldWords: [
      { word: "coding", index: 7 },
      { word: "testing", index: 17 },
    ],
    italicWords: [],
    underlinedWords: [{ word: "project", index: 9 }],
    lineCrossedWords: [],
  },
  {
    id: "mnb;vcd",
    title: "Buy groceries",
    content: "Get milk, bread , and cheese",
    background: "hsl(210,50%,50%)",
    size: 30,
    category: "Shopping",
    creationDate: new Date("2023-04-22T10:30:00.000Z"),
    expirationDate: new Date("2023-04-22T10:30:00.000Z"),
    isPinned: false,
    isHidden: false,
    boldWords: [],
    italicWords: [],
    underlinedWords: [],
    lineCrossedWords: [{ word: "bread", index: 2 }],
  },
  {
    id: "qwe;ajkl",
    title: "Complete project",
    content:
      "Finish coding and testing Material Symbols are our newest icons Finish coding and testing Material Symbols are our newest icons",
    background: "hsl(50,80%,50%)",
    size: 40,
    category: "Work",
    creationDate: new Date("2023-04-22T10:30:00.000Z"),
    expirationDate: new Date("2023-04-22T10:30:00.000Z"),
    isPinned: true,
    isHidden: false,
    boldWords: [
      { word: "coding", index: 1 },
      { word: "testing", index: 3 },
    ],
    italicWords: [],
    underlinedWords: [{ word: "coding", index: 11 }],
    lineCrossedWords: [],
  },
  {
    id: "zxc;asd",
    title: "Read book",
    content: "Finish chapter 3",
    background: "hsl(330,70%,50%)",
    size: 20,
    category: "Leisure",
    creationDate: new Date("2023-04-22T10:30:00.000Z"),
    expirationDate: new Date("2023-04-22T10:30:00.000Z"),
    isPinned: false,
    isHidden: true,
    boldWords: [{ word: "chapter 3", index: 7 }],
    italicWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
    underlinedWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
    lineCrossedWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
  },
  {
    id: "zxc;asajd",
    title: "Read book",
    content: "Finish chapter 3",
    background: "hsl(170,70%,50%)",
    size: 20,
    category: "Leisure",
    creationDate: new Date("2023-04-22T10:30:00.000Z"),
    expirationDate: new Date("2023-04-22T10:30:00.000Z"),
    isPinned: false,
    isHidden: false,
    boldWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
    italicWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
    underlinedWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
    lineCrossedWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
  },
  {
    id: "poi;uyt",
    title: "Call mom",
    content: "Ask about her health",
    background: "hsl(90,60%,50%)",
    size: 25,
    category: "Family",
    creationDate: new Date("2023-04-22T10:30:00.000Z"),
    expirationDate: new Date("2023-04-22T10:30:00.000Z"),
    isPinned: false,
    isHidden: false,
    boldWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
    italicWords: [{ word: "health", index: 12 }],
    underlinedWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
    lineCrossedWords: [
      { word: "Finish", index: 0 },
      { word: "chapter 3", index: 7 },
    ],
  },
];
